---
title: "Análise da gestão ambiental de municípios brasileiros pela Teoria da Resposta ao Item"
output:
  pdf_document:
    latex_engine: lualatex
    pandoc_args: --listings
    includes:
      in_header: preamble.tex
geometry: columnsep=3em
---


```{r setup, include=FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE, 
  comment=">",
  prompt=T,
  fig.align='center',
  size="small")


options(
  scipen=999,
  knitr.kable.NA = '',
  knitr.table.bottomrule = "\\specialrule{.3pt}{0pt}{1pt}\\specialrule{.3pt}{0pt}{0pt}",
  knitr.table.toprule    = "\\specialrule{.3pt}{0pt}{1pt}\\specialrule{.3pt}{0pt}{0pt}",
  knitr.table.midrule    = "\\specialrule{.3pt}{0pt}{1pt}")


if(!require(kableExtra)) install.packages("kableExtra"); library(kableExtra)
if(!require(readxl)) install.packages("readxl"); library(readxl)
if(!require(formatR)) install.packages("formatR"); library(formatR)
if(!require(xtable)) install.packages("xtable"); library(xtable)
if(!require(tidyverse)) install.packages("tidyverse"); library(tidyverse)
if(!require(factoextra)) install.packages("factoextra"); library(factoextra)
if(!require(RColorBrewer)) install.packages("RColorBrewer"); library(RColorBrewer)
if(!require(irtoys)) install.packages("irtoys"); library(irtoys)


# Funções

# função para converter uma matrix em tex
texMatrix <- function(matrix, round = 2){
  matrix <- round(matrix,round)
  tex <- ""
  for(i in 1:nrow(matrix)){
    if(i != nrow(matrix)){
      tex <- paste0(tex,paste(matrix[i,],collapse = " & ")," \\\\ ")
    }else{
      tex <- paste0(tex,paste(matrix[i,],collapse = " & "))
    }
    
  }
  
  paste0("\\begin{pmatrix}",tex,"\\end{pmatrix}")
}
```

**Alunos:**

Leandro Alves da Silva - nº USP: 11868023

Thiago Ferreira Miranda - nº USP: 11925711

```{r}
load("data.RData")
```


```{r Análise Clássica 1, echo = FALSE, results = 'asis', warning = F}
# Análise por scores
tct_1 <- data.frame(tct$perc) |> 
  rename(prop0=X0,prop1=X1) |> 
  mutate(bisCorr=tct$bisCorr) |> 
  mutate(ExBisCorr=tct$ExBisCorr) 

t1.1 <- tct_1[1:43,] 

t1.1 <- t1.1 |>
  round(2)|>
  kbl(format = "latex",linesep="") |> 
  column_spec(1:6, background = ifelse(t1.1$bisCorr > 0.4 , "lightgray", "white"))

t1.2 <- tct_1[44:86,] 

t1.2 <- t1.2 |>
  round(2) |> 
  kbl(format = "latex",linesep="") |> 
  column_spec(1:6, background = ifelse(t1.2$bisCorr > 0.4 , "lightgray", "white"))

cat(c("\\begin{table}[h] \\caption{TCT - Proporção de resposta por nível e coeficientes de correlação ponto bisserial.} \\centering \\tiny", 
      t1.1,
    "\\hspace{0cm} \\centering ",
      t1.2,
    "\\end{table}"))
```

\newpage

```{r Análise Clássica 2, echo = FALSE, results = 'asis', warning = F}
tct_2 <- data.frame(alpha=tct$alpha) |> 
  round(4)


t2.1 <- tct_2 |> 
  slice(1:44) 

t2.1 <- t2.1 |>
  rename(alpha=value) |> 
  kbl(format = "latex",linesep="") |> 
  column_spec(1:2, background = ifelse(t2.1$value < 0.8812 , "lightgray", "white"))

t2.2 <- tct_2|> 
  slice(45:87) 

t2.2 <- t2.2 |>
  rename(alpha=value) |> 
  kbl(format = "latex",linesep="") |> 
  column_spec(1:2, background = ifelse(t2.2$value < 0.8812 , "lightgray", "white"))

cat(c("\\begin{table}[h] \\caption{TCT - Alpha de Cronbach.} \\centering \\tiny", 
      t2.1,
    "\\hspace{0cm} \\centering ",
      t2.2,
    "\\end{table}"))
```

\newpage


```{r Análise TRI}
data.frame(itens_parametros$est) |> 
  setNames(c("a","b","c")) |> 
  rownames_to_column("item.id") |> 
  right_join(itens_selecionados,by="item.id") |> 
  dplyr::select(item.id,item.descricao,a,b)|> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",align=c("l","l","c","c"),
      caption = "Itens que permaneceram na análise.") |> 
  kable_styling(font_size=5) |> 
  column_spec(2, width = "50em")

```

\newpage
```{r leitura e tratamento dos dados}


dicionario |> 
  filter(secao.id=="5.1") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Órgão gestor do meio ambiente.") |> 
  kable_styling(font_size=5)

dicionario |> 
  filter(secao.id=="5.2") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Capacitação.") |> 
  kable_styling(font_size=5) |> 
  column_spec(2, width = "50em")

dicionario |> 
  filter(secao.id=="5.3") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Conselho e Fundo municipal de meio ambiente.") |> 
  kable_styling(font_size=5) |> 
  column_spec(2, width = "50em")

dicionario |> 
  filter(secao.id=="5.4") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Legislação ou instrumento de gestão ambiental.") |> 
  kable_styling(font_size=5)

dicionario |> 
  filter(secao.id=="5.6") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Plano de Gestão Integrada de Resíduos Sólidos.") |> 
  kable_styling(font_size=5) |> 
  column_spec(2, width = "50em")

dicionario |> 
  filter(secao.id=="5.7") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Programas em parceria com o Governo Federal.") |> 
  kable_styling(font_size=5) |> 
  column_spec(2, width = "50em")

dicionario |> 
  filter(secao.id=="5.8") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Pagamento de Serviços Ambientais.") |> 
  kable_styling(font_size=5) |> 
  column_spec(2, width = "50em")

dicionario |> 
  filter(secao.id=="5.9") |> 
  dplyr::select(-c(1,2)) |> 
  kbl(format = "latex",escape = FALSE,booktabs = F,longtable = T,linesep="",
      caption = "Seção - Impacto Ambiental e/ou processo/ação que resulte em impacto no ambiente.") |> 
  kable_styling(font_size=5) |> 
  column_spec(2, width = "50em")

```

\pagebreak










































